### ISSUE TITLE
Using Jinja2 for loops

### ISSUE THREAD

**Issue by lukas-koschmieder** [fralau/mkdocs_macros_plugin#11]
I have trouble using Jinja2 for loops in mkdocs_macros_plugin.

### mkdocs.yml

```yaml
plugins:
  - search
  - macros

extra:
  files:
    foo:
      name: 'Foo'
    bar:
      name: 'Bar'
```

### index.md

```markdown
{% for file in files %}
- {{ file.name }}
{% endfor %}
```

### Expected index.html

```markdown
- Foo
- Bar
```

### Actual index.html

```markdown
- 
- 
```
