### ISSUE TITLE
Question for create md files from extra vars

### ISSUE THREAD

**Issue by alanlivio** [fralau/mkdocs_macros_plugin#131]
I know that `mkdcos-macros-plugin` enable the use of the `extra` variables from the mkdocs.yaml
```yaml
extra:
   data_for_page1
   data_for_page2
```
Such variables can be in existing markdown files, e.g., page.md uses `extra.data_for_page1` and page2.md uses `extra.data_for_page2`.

I am wondering if it is possible to use such variables to make mkdcos create the page1.md/page2.md files itself.

**Comment by fralau** [comment]
You mean, dynamically generating _new_ markdown pages? 🤔 

Interesting idea. Is the number of pages variable or static? Could you perhaps elaborate on your use case?

**Comment by alanlivio** [comment]
> You mean, dynamically generating new markdown pages? 🤔
Yes

>Interesting idea. Is the number of pages variable or static? Could you perhaps elaborate on your use case?
I think that may depend on the list of `extra` variables. 
Image the next mkdocs.yaml and I will create one page for each given icon/url.
```yml
extra:
   new_pages: 
      -  icon: "<url>"
          url: "<url>"
      -  icon: "<url>"
          url: "<url>"
```
