### ISSUE TITLE
Add an option to raise exception if render fails

### ISSUE THREAD

**Issue by allebacco** [fralau/mkdocs_macros_plugin#133]
The current behavior of the `MacrosPlugin.render()` method when the template rendering fails is to return the exception message as the rendered text.

This behavior is convenient when writing the mkdocs pages, but it is less useful when documentation is compiled in a CI/CD environment.

My proposal is to add an option to raise an exception when the rendering fails, in this way the CI/CD process can fail. Otherwise the compiled documentation will miss the relevant information because of the error message of the macros plugin.

The option could be named `strict` and should be false to keep the current behavior of the plugin.

Thanks to mkdocs 1.2, the option could then be configured with an environment variable like:

```yaml
plugins:
  - search
  - macros:
      module_name: my_module
      strict: !ENV [ENABLE_STRICT_MODE, false]
```

In this way, local execution will not raise exception, but execution within CI/CD pipelines could raise exceptions in case of rendering errors.

**Comment by fralau** [comment]
Thanks a lot! Yes, it is true that the choice of rendering the template interpretation error itself, was to help debugging.

If my understanding is correct, you are in a CD/CI context, you wish to set an option that instructs mkdocs-macros to fail in case of rendering error (as e.g. in compilation); and ideally, to provide a return code so that the automation script/tool could pick it up and initiate some adequate exception processing?  

At a first glance, it makes sense to me 🤔 .

If yes (and to keep things simple) could something more or less like this work?

```yaml
plugins:
  - search
  - macros:
      module_name: my_module
      fail_on_error: true
```

**Comment by allebacco** [comment]
@fralau Yes, that's will be optimal. Thanks

**Comment by fralau** [comment]
All right, I am implementing it this way:

```yaml
plugins:
  - search
  - macros:
      module_name: my_module
      on_error_fail: true
```

In case of macro syntax or rendering error the return code will be 100.

Would that work for you?

Just curious: what would be the meaning of `!ENV [ENABLE_STRICT_MODE, false]`? Is it something specific to your Python YAML implementation?
