### ISSUE TITLE
Configurable YAML data file

### ISSUE THREAD

**Issue by nathanph** [fralau/mkdocs_macros_plugin#15]
Hi @fralau, I love your macros plugin and use it almost every day! :heart: 

Feature request incoming though. :stuck_out_tongue_winking_eye:

## Feature Request

I would like the ability to configure the macros plugin with YAML data files to initialize the `env.variables` dictionary with.

**Example `mkdocs.yml`**

```yaml
###########
# Plugins #
###########
plugins:
  # Macros
  - macros:
      data:
        - 'data/authors.yaml'  # A YAML file containing information about authors.
        - 'data/projects.yaml' # A YAML file containing information about projects.
```

My expectation would be that `extra` from the `mkdocs.yml` is still initialized into the `env.variables` dictionary, but that any additional data files supplied would merge into `env.variables`, potentially overriding the values picked up from the `extra` property. The latest file loaded would take precedence.

## Reasoning

I'm using the mdocs-macros-plugin for a pretty large documentation site.

At this point **our `mkdocs.yml` is filled to the brim with data** from the `extra` object of our project. This smells of an anti-pattern to me. I'd prefer, if possible, not to mix MkDocs configuration with documentation data.

*I realize that I could do this myself in Python!*

However, it seems to me like mixing data with configuration is really a bad practice. I'd be willing to wager that lots of people have wanted this functionality, or at least would use it if it were available, but haven't bothered to open an issue or write up a feature request. 

Thanks @fralau!

**Comment by fralau** [comment]
I am grateful for your appreciation. When someone comes up with a totally unexpected, but meaningful feature request, it means we are perhaps on the right track.

Plus, 
> I'm using the mdocs-macros-plugin for a pretty large documentation site.

That's doubly close to my heart, because 1) you are good enough to consider this for some serious application 2) I have done a lot of documentation myself during my career. ... so you have my full individed attention.

Let me express what I get from this use case, in my own words: there is a static, mkdocs-produced website, which makes use of variables exploited in jinja2 directives with the `macro` plugin. 

At this point the data are no longer only **configuration** data (environment, repetitive snippets, etc.) to help build the website, but it has started including **documentation** information that is pertinent to the subject you are documenting. As a result, the mkdocs.yml file started growing with domain-specific information.

By using external yml files, we would be able to cleanly separate the configuration data from the documentation data. People in charge of maintaining that information would not mess with the general configuration of the website; they might be even different persons.

Is my understanding correct?

**Comment by nathanph** [comment]
> At this point the data are no longer only configuration data (environment, repetitive snippets, etc.) to help build the website, but it has started including documentation information that is pertinent to the subject you are documenting. As a result, the mkdocs.yml file started growing with domain-specific information.

Fucking *nailed it!* :1st_place_medal:

> By using external yml files, we would be able to cleanly separate the configuration data from the documentation data. People in charge of maintaining that information would not mess with the general configuration of the website; they might be even different persons.

Precisely! There are a lot of actors involved here, but to break them into what I would consider their natural ontology: _technical users_ and _non-technical users_.

- The _technical users_, such as myself and other developers, who are happy to hack away are variables in a Python file or the MkDocs configuration file.

  _But mixing data with code or configuration feels wrong._ :hear_no_evil: :see_no_evil: :speak_no_evil:

- The _non-technical users_, such as management, who are less-likely to want to touch a Python file or the MkDocs configuration file.

  _And frankly, I don't want them to either!_
  _They're liable to break things._ :skull:

Some other benefits to segregating the data include discoverability, namespacing, and the ability to more-easily integrate data with CI/CD pipelines.

## Example

Part of our documentation data, currently in the `extra` property of our `mkdocs.yml`, includes some team information: the team name, its team members, their relevant Slack information, etc.

I would like to segregate all of this data into a separate file, e.g., `data/team.yaml`; _and ideally get rid of the extra level of nesting caused by everything needing to exist within the `extra` property._

Documentation editors could then edit this data file without worrying about side-effects it might cause, i.e., Team members could be gracefully and easily removed, updated, etc.

**Team Information**

```yaml
extra:
  ###
  # Team Members
  #
  # We've found it useful to define many things at the root-level to make
  # referencing them in documentation more simple and concise.
  #
  # E.g., to get a user's email, `{{ joe.email }}`.
  ###
  joe: &joe
    name: 'Joe Bob'
    email: 'joe.bob@email.com'
    slack:
      name: '@joe'
      id: 'ABC123'
    role: 'Development Director'
    squad: ''
  jeff: &jeff
    name: 'Jeff Lane'
    email: 'jeff.lane@email.com'
    slack:
      name: '@jeff'
      id: '123ABC'
    role: 'Release Manager'
    squad: ''
  # Lots more people here...
  nate: &nate
    name: 'Nathan pH'
    email: 'nathanph@gmail.com'
    slack:
      name: '@nateph'
      id: 'A177RRFRC'
    role: 'Engineer'
    squad: 'Services'

  ###
  # Team Information
  #
  # We still get the flexibility of collections and namespacing of our
  # root-level objects by leveraging anchors and references.
  #
  # E.g., to get all of the team members, `{{ team.members }}`.
  ###
  team:
    name: 'Team Foo'
    description: 'We build broken things!'
    slack:
      name: '#team-foo'
    members:
      - *joe
      - *jeff
      # ...
      - *nate
```

**Thanks for taking the time to review my feature request!** :heart:

**Comment by fralau** [comment]
I have pushed a new version that should do what you suggested.

In the `mkdocs.yml` file, it would look like this:
```
plugins:
    - search
    - macros:
        include_yaml: 
          - foo.yaml
          - bar.yaml
```
- The location of each file is relative to the project directory (so you could place all files e.g. in a `/data` directory
- It will load the variables from each yaml file in succession. In case of conflict in a tree of dictionaries, it will try to smartly combine the nodes, while overriding conflicts (the later ones override the earlier ones).

Could you check whether it is working for you?
