### ISSUE TITLE
Access plugin's parameters

### ISSUE THREAD

**Issue by fralau** [fralau/mkdocs_macros_plugin#45]
It can be useful to access the arguments in the config file, e.g.:

```yaml
plugins:
  ...
  - macros:
      module_name: mymodule
      include_dir: include
```

As `{{ plugin.module_name }}` or `{{ plugin.include_dir }}`.
