### ISSUE TITLE
Macros get ran while in code block

### ISSUE THREAD

**Issue by LilTrublMakr** [fralau/mkdocs_macros_plugin#57]
While making a 'contributing' page, I have found that when I insert the macro within a markdown code block, the macro gets parsed and not nullified like everything else in the code block.

My use:
mkdocs.yml
```
extra:
  table:
    head: '| Application | Usage | Website | Github | Docker Hub |'
    head2: '|-|-|-|-|-|'
```

contribute.md
```
\```
{{ table.head }}
{{ table.head2 }}
\```
```
(backslashes added to cancel the close, they are not actually in the file)

contribute.md will actually get parsed and show 
```
| Application | Usage | Website | Github | Docker Hub |
|-|-|-|-|-|
```
instead of showing `{{ table.head }}` and `{{ table.head2 }}` like I was expecting it to. I am trying to make this a copy and paste template for any new pages so I really don't want to add a character before hand to break it.

I can see how this is expected behavior but I would like it to stay unparsed within the code block in case I need to change the table in the future, I wouldn't have to go in and change the table for each file.
